### ISSUE TITLE
How initiate build?

### ISSUE THREAD

**Issue by Ma3yTa** [stack72/TeamCitySharp#109]

**Comment by borismod** [comment]
I am not sure there is a method for running a build in TeamCitySharp. You may want to take a look at FluentTc library which allows this easily:

```C#
new RemoteTc()
   .Connect(a => a.ToHost("tc")
   .AsUser("MYUSERNAME", "MYPASSWORD"))
   .RunBuildConfiguration(_ => _.Id("bt2"));
```

For more examples see wiki:
https://github.com/QualiSystems/FluentTc/wiki/RemoteTc

**Comment by Ma3yTa** [comment]
@borismod thanks
